#!/usr/bin/env bash

# This file is meant to be used in containers to start the java process with correct parameters

if ! (echo "${@}" | grep -e "--debug" -q)
then
    LOG_APPENDER="-Dlogappender=STDOUT"
fi

CLASSPATH="${INSTALL_DIR}/puppet-server-release.jar"

cli_defaults="${INSTALL_DIR}/cli/cli-defaults.sh"
if [ -e "$cli_defaults" ]; then
  . "$cli_defaults"
  if [ $? -ne 0 ]; then
    echo "Unable to initialize cli defaults, failing start." 1>&2
    exit 1
  fi
fi

COMMAND="${JAVA_BIN} ${JAVA_ARGS} ${LOG_APPENDER} \
         -cp '${CLASSPATH}' \
         clojure.main -m puppetlabs.trapperkeeper.main \
         --config ${CONFIG} --bootstrap-config ${BOOTSTRAP_CONFIG} \
         ${TK_ARGS} \
         ${@}"

pushd "${INSTALL_DIR}" &> /dev/null
if [ "$EUID" = "0" ] && command -v runuser &> /dev/null; then
  runuser "${USER}" -s /bin/bash -c "$COMMAND"
elif [ "$EUID" = "$(id -u ${USER})" ]; then
  /bin/bash -c "$COMMAND"
elif command -v sudo &> /dev/null; then
  sudo -H -u "${USER}" $COMMAND
else
  su "${USER}" -s /bin/bash -c "$COMMAND"
fi
popd &> /dev/null
