name: Clojure Linting

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths: ['src/**','test/**','.clj-kondo/config.edn','project.clj','.github/**']

jobs:
  clojure-linting:
    name: Clojure Linting
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: checkout repo
        uses: actions/checkout@v4
      # newer versions cause lint errors
      # https://github.com/clj-kondo/clj-kondo/releases
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          clj-kondo: 2025.02.20
      - name: kondo lint
        run: clj-kondo --lint src test
