---
name: PR Testing

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pr-testing:
    name: PR Testing
    strategy:
      fail-fast: false
      matrix:
        javaargs: ['with-profile fips', '']
        filter: [':singlethreaded', ':multithreaded']
        version: ['11', '17']
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      # We don't install the system package here because it will install Java 21
      # The lein script we have in the repo came from
      # https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      - name: install lein
        run: cp ./lein /usr/local/bin
      - name: setup gems
        run: ./dev-setup
      - name: clojure tests
        run: lein -U ${{ matrix.javaargs }} test ${{ matrix.filter }}
        timeout-minutes: 30
      - name: rspec tests
        run: rake spec
